version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - mongodb
      - elasticsearch
    env_file:
      - backend.env
    working_dir: /app

  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - backend.env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    env_file:
      - backend.env
    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio-data:/data'
    env_file:
      - backend.env
    command: server --console-address ":9001" /data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - discovery.type=single-node
      
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      
      - bootstrap.memory_lock=true
      - indices.query.bool.max_clause_count=10000
    
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    
    ports:
      - "9200:9200"
      - "9300:9300"
    
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_logs:/usr/share/elasticsearch/logs
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  es-sync-cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - ./backend:/app
      - cron_logs:/var/log
    env_file:
      - backend.env
    depends_on:
      - mongodb
      - elasticsearch

volumes:
  db_data:
  mongodb_data:
  minio-data:
  elasticsearch_data:
  elasticsearch_logs:
  cron_logs: 
