FROM node:20-slim

WORKDIR /app



COPY frontend/ ./
# Copy package management files
COPY package.json yarn.lock* ./

# Copy config files
COPY postcss.config.cjs tailwind.config.cjs vite.config.js ./

# Install dependencies
RUN yarn install --frozen-lockfile

# List installed packages for debugging
RUN ls -la node_modules/.bin

# Copy the rest of the application code
COPY . .

EXPOSE 5173

CMD [ "yarn", "dev", "--", "--host", "0.0.0.0" ]
