FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1


RUN apt-get update && apt-get install -y cron
COPY backend/cron/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY cron.sh /cron.sh

RUN chmod +x /cron.sh

ENTRYPOINT ["/cron.sh"]


