FROM node:20-slim

WORKDIR /app

COPY frontend/ ./
COPY package.json yarn.lock* ./

COPY postcss.config.cjs tailwind.config.cjs vite.config.js ./

RUN yarn install --frozen-lockfile
RUN ls -la node_modules/.bin

COPY . .

EXPOSE 5173

CMD [ "yarn", "dev", "--", "--host", "0.0.0.0" ]
