services:
  devthoughts:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    env_file:
      - example.env
    working_dir: /app
  
  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - example.env

volumes:
  db_data: